sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf.srm &
