sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./ga/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/brasilia/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
sleep 2 &
sbatch ./pso/rio/job_dsf_shared.srm &
